"""Skeleton service — generates logical skeletons by stripping mechanical bloat.

Uses language-aware prompts to identify and remove boilerplate while
preserving core algorithms, design patterns, and critical logic.
"""

import json
import logging
from typing import Dict, Any

from app.services.llm_service import llm_service, TaskType
from app.services.language_service import detect_language, get_language_prompt_context, is_expert_language
from app.services.security_service import (
    prepare_secure_input,
    sentinel_validate,
    SentinelVerdict,
    SHIELDED_SYSTEM_PREAMBLE,
)

logger = logging.getLogger(__name__)

def _clean_json_string(json_str: str) -> str:
    r"""Fix common invalid JSON escapes generated by LLMs (e.g., regex \d or windows paths)."""
    import re
    # 1. Temporarily replace valid escaped backslashes `\\` with a placeholder
    temp = json_str.replace('\\\\', '__ESCAPED_SLASH__')
    
    # 2. Now any remaining `\` is either a valid JSON escape char `\n` `\"` etc, or an invalid one (`\d` `\w` `\e`).
    # We replace any `\` that is NOT followed by a valid JSON escape char with `\\`
    temp = re.sub(r'\\(?![\\"/bfnrtu])', r'\\\\', temp)
    
    # 3. Restore the valid escaped backslashes
    cleaned = temp.replace('__ESCAPED_SLASH__', '\\\\')
    return cleaned


SKELETON_SYSTEM_PROMPT = """You are CogniCode, an expert code analyst. Your job is to create "Logical Skeletons" — 
simplified versions of source code that expose the core algorithms, design patterns, and critical logic 
while stripping away mechanical bloat.

RULES:
1. PRESERVE: Core algorithms, business logic, state machines, design patterns, error handling logic, type signatures
2. REMOVE: Redundant boilerplate, unused imports, auto-generated code, repetitive CRUD, verbose comments that restate code
3. SIMPLIFY: Verbose error handling → concise patterns, repetitive similar methods → representative examples with "// ... N similar methods" 
4. ANNOTATE: Add brief "// WHY:" comments on non-obvious logic

Output ONLY valid code (the skeleton). Do not wrap in markdown code blocks.
"""

REMOVAL_LOG_SYSTEM_PROMPT = """You are CogniCode, an expert code analyst. Analyze the original source code and the skeleton version.
Generate a detailed removal log explaining what was removed and why.

Output a JSON array where each item has:
- "item": short description of what was removed (e.g., "unused import os")
- "reason": why it's mechanical bloat (e.g., "imported but never used in any function")  
- "type": category — one of: "unused_import", "boilerplate", "redundant_code", "auto_generated", "verbose_comment", "dead_code"
- "lines": approximate original line range as string (e.g., "1-5")

Output ONLY valid JSON array. No markdown, no explanation.
"""

LOGICAL_CORE_SYSTEM_PROMPT = """You are CogniCode, an expert code educator. Explain the logical core of this skeleton code.
Focus on:
1. What algorithms or patterns are used and why
2. How the key functions work together
3. The data flow through the code
4. Any clever or non-obvious implementations

Write in clear, educational prose. Use bullet points for lists. 
Reference specific function/class names.Keep it concise but thorough.
"""

FILE_CONTEXT_SYSTEM_PROMPT = """You are CogniCode. Given a file and the project's tech stack/overview, 
explain this file's role within the project architecture.

Cover:
1. What responsibility this file handles
2. What other parts of the system likely depend on it
3. Where it sits in the dependency graph (core utility? API layer? business logic?)
4. How it contributes to the overall system design

Be specific to THIS file. Keep it to 3-5 sentences.
"""

TRIAGE_SYSTEM_PROMPT = """You are an expert software architect. Analyze the provided list of file paths.
Categorize each file as either "keep" (core logic, routing, complex utilities, state management, complex components)
or "discard" (boilerplate, standard configs, generated lockfiles, simple constants, __init__.py, etc).

Output ONLY a JSON object with two arrays:
{
  "keep": ["path1", "path2"],
  "discard": ["path3", "path4"]
}
"""

BATCH_MAPPING_SYSTEM_PROMPT = r"""You are CogniCode, an expert code analyst. Generate "Logical Skeletons" and brief summaries for a batch of files.

RULES FOR SKELETONS:
1. PRESERVE: Core algorithms, business logic, design patterns, types
2. REMOVE: Redundant boilerplate, imports, simple CRUD
3. SIMPLIFY: Verbose error handling → concise patterns
4. ANNOTATE: Add brief "// WHY:" comments on non-obvious logic
CRITICAL JSON RULES:
- Output ONLY a valid JSON array of objects.
- You MUST properly escape ALL backslashes inside JSON string values. For example, a regex `\d` must be `\\d`, and `C:\path` must be `C:\\path`.
- You MUST properly escape all double quotes (`\"`) inside strings.

Each object must have:
- "path": The file path
- "skeleton": The simplified logical skeleton code (as a string, MUST BE properly JSON escaped)
- "summary": A structured markdown explanation of the file's role within the architecture. Focus ONLY on the WHAT and WHERE: provide a short summary, explain its exact responsibilities, and list its structural dependencies (what it relies on, and what relies on it).
- "logical_core": A highly detailed, structured markdown explanation of the internal mechanics. Focus ONLY on the HOW: explain the specific algorithms, techniques, design patterns, and step-by-step logic used in the skeleton to help a learner fully understand the technical implementation.
- "removal_log": A JSON array of objects detailing what was removed (keys: "item", "reason", "type", "lines"). "type" must be one of: "unused_import", "boilerplate", "redundant_code", "auto_generated", "verbose_comment", "dead_code". If nothing was removed, make it an empty array [].
"""


async def generate_skeleton(file_path: str, content: str) -> str:
    """Generate a logical skeleton with security layers applied."""
    language = detect_language(file_path) or "unknown"
    lang_context = get_language_prompt_context(language)

    # Layer 1+2: Strip comments and wrap in XML delimiters
    secured_code = prepare_secure_input(content, file_path, language)

    prompt = f"""Language Context: {lang_context}

File: {file_path}

{secured_code}

Generate the Logical Skeleton for this code. Preserve core logic, remove mechanical bloat.
Output ONLY valid code."""

    # System prompt includes security preamble
    system = SHIELDED_SYSTEM_PREAMBLE + "\n\n" + SKELETON_SYSTEM_PROMPT
    if is_expert_language(language):
        system += f"\n\nYou are an expert in {language}. Apply deep language-specific knowledge."

    skeleton = await llm_service.generate(
        prompt=prompt,
        task_type=TaskType.MAPPING,
        system_prompt=system,
        temperature=0.2,
    )

    # Layer 3: Sentinel validation on output
    verdict, explanation = await sentinel_validate(
        skeleton, context=f"Skeleton for {file_path}", use_llm=False  # Static-only for speed
    )
    if verdict == SentinelVerdict.BLOCKED:
        logger.warning(f"Sentinel blocked skeleton for {file_path}: {explanation}")
        return f"// SECURITY: Skeleton generation blocked by Sentinel.\n// Reason: {explanation}\n// Original code preserved for manual review."

    return skeleton


async def filter_triage_files(file_list: list[str]) -> tuple[list[str], list[str]]:
    """Triage pass: Split files into Keep vs Discard based on paths."""
    prompt = "Categorize these files:\n" + "\n".join(file_list)
    
    try:
        result = await llm_service.generate(
            prompt=prompt,
            task_type=TaskType.TRIAGE,
            system_prompt=TRIAGE_SYSTEM_PROMPT,
            temperature=0.0
        )
        
        # Clean markdown
        result = result.strip()
        if result.startswith("```"):
            result = result.split("\n", 1)[-1].rsplit("```", 1)[0].strip()
            
        result = _clean_json_string(result)
        data = json.loads(result)
        return data.get("keep", []), data.get("discard", [])
    except Exception as e:
        logger.error(f"Triage failed, failing open (keeping all): {e}")
        return file_list, []


async def generate_batch_skeletons(file_batch: list[dict]) -> list[dict]:
    """Batch Map pass: Extract skeletons and summaries for multiple files in one LLM call."""
    prompt = "Analyze the following batch of files:\n\n"
    for item in file_batch:
        prompt += f"=== FILE: {item['path']} ===\n{item['content']}\n\n"
        
    try:
        result = await llm_service.generate(
            prompt=prompt,
            task_type=TaskType.MAPPING,
            system_prompt=BATCH_MAPPING_SYSTEM_PROMPT,
            temperature=0.2
        )
        
        result = result.strip()
        if result.startswith("```"):
            result = result.split("\n", 1)[-1].rsplit("```", 1)[0].strip()
            
        result = _clean_json_string(result)
        return json.loads(result)
    except Exception as e:
        logger.error(f"Batch mapping failed: {e}")
        return []


async def generate_removal_log(file_path: str, original: str, skeleton: str) -> str:
    """Generate a JSON removal log comparing original to skeleton."""
    prompt = f"""File: {file_path}

=== ORIGINAL CODE ===
{original}

=== SKELETON CODE ===
{skeleton}

Generate the removal log as a JSON array."""

    result = await llm_service.generate(
        prompt=prompt,
        task_type=TaskType.MAPPING,
        system_prompt=REMOVAL_LOG_SYSTEM_PROMPT,
        temperature=0.1,
    )

    # Clean and validate JSON
    result = result.strip()
    if result.startswith("```"):
        result = result.split("\n", 1)[-1].rsplit("```", 1)[0].strip()

    result = _clean_json_string(result)

    try:
        json.loads(result)  # Validate it's valid JSON
        return result
    except json.JSONDecodeError:
        logger.warning(f"Invalid JSON in removal log for {file_path}, wrapping in array")
        return "[]"


async def generate_logical_core(file_path: str, skeleton: str) -> str:
    """Generate an explanation of the skeleton's logical core."""
    language = detect_language(file_path) or "unknown"

    prompt = f"""Language: {language}
File: {file_path}

Skeleton Code:
```
{skeleton}
```

Explain the logical core — the algorithms, patterns, and key logic in this skeleton."""

    return await llm_service.generate(
        prompt=prompt,
        task_type=TaskType.SYNTHESIS,
        system_prompt=LOGICAL_CORE_SYSTEM_PROMPT,
        temperature=0.3,
    )


async def generate_file_context(
    file_path: str, content: str, project_overview: str, tech_stack: str
) -> str:
    """Generate an explanation of this file's role in the project."""
    prompt = f"""Project Overview: {project_overview}
Tech Stack: {tech_stack}

File: {file_path}
File Content (first 100 lines):
```
{chr(10).join(content.split(chr(10))[:100])}
```

Explain this file's role in the project architecture."""

    return await llm_service.generate(
        prompt=prompt,
        task_type=TaskType.SYNTHESIS,
        system_prompt=FILE_CONTEXT_SYSTEM_PROMPT,
        temperature=0.3,
    )


async def generate_project_overview(file_list: list[str], tech_stack: Dict[str, Any]) -> str:
    """Generate a high-level project overview from the file list and tech stack."""
    prompt = f"""Analyze this repository structure and tech stack to create a concise project overview.

Tech Stack Detected: {json.dumps(tech_stack)}

File Structure (sample):
{chr(10).join(file_list[:80])}
{"... and " + str(len(file_list) - 80) + " more files" if len(file_list) > 80 else ""}

Write a clear architectural overview covering:
1. What this project does (purpose)
2. Architecture pattern used (monolith, microservices, MVC, etc.)
3. Key components and their responsibilities
4. How components interact

Keep it concise — 1-2 paragraphs max."""

    return await llm_service.generate(
        prompt=prompt,
        task_type=TaskType.SYNTHESIS,
        system_prompt="You are CogniCode, an expert software architect. Analyze repository structure and provide clear architectural summaries.",
        temperature=0.3,
    )


def estimate_confidence(original: str, skeleton: str) -> float:
    """
    Estimate confidence score (0-100) based on reduction ratio and heuristics.
    Higher confidence = more certain that removal is correct.
    """
    orig_lines = len(original.strip().split("\n"))
    skel_lines = len(skeleton.strip().split("\n"))

    if orig_lines == 0:
        return 50.0

    reduction_ratio = 1 - (skel_lines / orig_lines)

    # Sweet spot: 20-60% reduction is most confident
    if 0.2 <= reduction_ratio <= 0.6:
        confidence = 85 + (reduction_ratio * 20)
    elif reduction_ratio < 0.2:
        # Very little removed — might be already clean
        confidence = 70 + (reduction_ratio * 50)
    elif reduction_ratio > 0.8:
        # Too much removed — might have lost important code
        confidence = max(40, 90 - (reduction_ratio * 60))
    else:
        confidence = 75 + (reduction_ratio * 15)

    return min(100.0, round(confidence, 1))
